CREATE DATABASE IF NOT EXISTS emrs_database;
USE emrs_database;

# Core Tables
CREATE TABLE IF NOT EXISTS User (   ID VARCHAR(255) PRIMARY KEY NOT NULL,   authCredentials VARCHAR(255) NOT NULL,   twoFactorEnabled BOOLEAN DEFAULT FALSE,   userType VARCHAR(255) NOT NULL     CHECK (userType IN ('Patient','Provider')) );
CREATE TABLE IF NOT EXISTS Patient (   ID VARCHAR(255) PRIMARY KEY,   medicalHistory TEXT,   allergyProfile TEXT,   insuranceDetails VARCHAR(255),   FOREIGN KEY (ID) REFERENCES User(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS HealthcareProvider (   ID VARCHAR(255) PRIMARY KEY,   providerID VARCHAR(255) NOT NULL UNIQUE,   FOREIGN KEY (ID) REFERENCES User(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Doctor (   ID VARCHAR(255) PRIMARY KEY,   specialization VARCHAR(100),   FOREIGN KEY (ID) REFERENCES HealthcareProvider(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Nurse (   ID VARCHAR(255) PRIMARY KEY,   FOREIGN KEY (ID) REFERENCES HealthcareProvider(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Administrator (   ID VARCHAR(255) PRIMARY KEY,   FOREIGN KEY (ID) REFERENCES HealthcareProvider(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS MedicalRecord (   recordID INT PRIMARY KEY AUTO_INCREMENT,   encodedData TEXT,   isLocked BOOLEAN DEFAULT FALSE,   patientID VARCHAR(255) NOT NULL,   FOREIGN KEY (patientID) REFERENCES Patient(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Visit (   visitID INT PRIMARY KEY AUTO_INCREMENT,   Purpose VARCHAR(255),   Time VARCHAR(255),   Date DATE,   WalkIn BOOLEAN DEFAULT FALSE,   recordID INT NOT NULL,   FOREIGN KEY (recordID) REFERENCES MedicalRecord(recordID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Billing (   billingID VARCHAR(255) PRIMARY KEY,   amount DOUBLE NOT NULL,   status VARCHAR(255) DEFAULT 'Pending',   patientID VARCHAR(255) NOT NULL,   FOREIGN KEY (patientID) REFERENCES Patient(ID)     ON DELETE CASCADE );

# Associative Tables
CREATE TABLE IF NOT EXISTS Visit_Doctor (   visitID INT,   doctorID VARCHAR(255),   PRIMARY KEY (visitID, doctorID),   FOREIGN KEY (visitID) REFERENCES Visit(visitID)     ON DELETE CASCADE,   FOREIGN KEY (doctorID) REFERENCES Doctor(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Visit_Nurse (   visitID INT,   nurseID VARCHAR(255),   PRIMARY KEY (visitID, nurseID),   FOREIGN KEY (visitID) REFERENCES Visit(visitID)     ON DELETE CASCADE,   FOREIGN KEY (nurseID) REFERENCES Nurse(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Visit_Administrator (   visitID INT,   adminID VARCHAR(255),   PRIMARY KEY (visitID, adminID),   FOREIGN KEY (visitID) REFERENCES Visit(visitID)     ON DELETE CASCADE,   FOREIGN KEY (adminID) REFERENCES Administrator(ID)     ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS Provider_MedicalRecord (   providerID VARCHAR(255),   recordID INT,   accessTime DATETIME DEFAULT CURRENT_TIMESTAMP,   PRIMARY KEY (providerID, recordID),   FOREIGN KEY (providerID)     REFERENCES HealthcareProvider(ID)     ON DELETE CASCADE,   FOREIGN KEY (recordID)     REFERENCES MedicalRecord(recordID)     ON DELETE CASCADE );

# INSERT INTO User (ID, authCredentials, twoFactorEnabled, userType) VALUES ('U001', 'hashed_password_123', TRUE, 'Patient');
# INSERT INTO Patient (ID, medicalHistory, allergyProfile, insuranceDetails) VALUES ('U001', 'Hypertension (2019)', 'Penicillin', 'BlueCross #BC-4821');